sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
script:
  - |
    for c in $(< commands.txt); do
      arr_c=(${c//:/ })  
      arr_p=(${arr_c[1]//;/ })  
      echo -e "#!/usr/bin/env bash\nset -Eeuo pipefail\nexec ${arr_c} \"$@\"" > entrypoint.sh
      docker build --build-arg REQUIRED_PACKAGES="$(echo ${arr_p[@]})" -t ${docker_org}/${arr_c}:${tag} .
    done
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script:
      - |
        for c in $(< commands.txt); do
          arr_c=(${c//:/ })  
          docker push ${docker_org}/${arr_c}:${tag}
        done
    on:
      branch: master
  - provider: script
    script:
      - |
        for c in $(< commands.txt); do
          arr_c=(${c//:/ })  
          docker push ${docker_org}/${arr_c}:${tag}
        done
    on:
      branch: master
      tags: true